urls :
  default : file:///Users/dawn/Documents/projects/rubycumwatir/app/index.html#/integration
  stubbed : file:///Users/dawn/Documents/projects/rubycumwatir/app/index.html#/functional
  
data :
  default : config/data/default
  mobile  : config/data/mobile

page_dir:
  default : ./src/bigweb/pages
  mobile  : ./src/mobile/pages

users :
  default : config/data/default/users.yml
  stubbed : config/data/default/users.yml

stub :
  wiremock :
    jar       : wiremock-standalone-2.3.1
    path      : config/stub
    port      : 8081
    root_dir  : config/stub
    verbose   : false

clients :
  default:
      browser: chrome
  firefox:
      browser: firefox
  ie:
      browser: ie
  iphone5:
    browser: chrome
    device : Apple iPhone 5
